name: example
description: Showcase Moon Design.
publish_to: none
version: 0.34.3
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.0.1
  moon_design:
    path: ../
  package_info_plus: ^3.0.2
  storybook_flutter:
    git:
      url: https://github.com/coingaming/storybook_flutter.git
      path: packages/storybook_flutter
  transparent_image: ^2.0.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/DMSans.ttf
  assets:
    - assets/images/
    - assets/svg/
