name: example
description: Showcase Moon Design.
publish_to: none
version: 1.1.0
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.1.1
  moon_design:
    path: ../
  package_info_plus: ^8.0.2
  storybook_flutter:
    git:
      url: https://github.com/coingaming/storybook_flutter.git
      ref: 506c73296c85a0bb970645036baa1c9213df1c6c
      path: packages/storybook_flutter
  transparent_image: ^2.0.1
  url_launcher: ^6.0.9
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
dependency_overrides:
  device_frame:
    git:
      url: https://github.com/bradrushworth/flutter_device_preview.git
      path: device_frame
  device_preview:
    git:
      url: https://github.com/bradrushworth/flutter_device_preview.git
      path: device_preview
flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/DMSans.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
  assets:
    - assets/code_snippets/
    - assets/components/
    - assets/images/
    - assets/svg/
